---
- hosts: localhost
  vars_files:
    - config.yml
  tasks:
    - name: Login to openshift
      command: oc login "{{ openshift.hostname }}" --insecure-skip-tls-verify=true --username="{{ openshift.username }}" --password="{{ openshift.password }}"
    - name: Set RH MAP Target
      fhc:
        action: target
        target: "{{ rhmap.domain }}"
    - name: Login to RH MAP
      fhc:
        action: login
        username: "{{ rhmap.username }}"
        password: "{{ rhmap.password }}"
    - name: Create MBaaS Target
      fhc:
        action: createMBaaSTarget
        mbaasName: "{{ project_name }}"
        fhMbaasHost: https://"{{ project_name }}"."{{ openshift.hostname }}"
        url: https://"{{ openshift.hostname }}":"{{ openshift.port }}"
        openshiftUsername: "{{ openshift.username }}"
        openshiftPassword: "{{ openshift.password }}"
        routerDNSUrl: "{{ openshift.wildcard_dns }}"
        environment: "{{ item.name }}"
      register: deployedmbaases
      with_items: 
        "{{ environments }}"
    - debug: 
        var: deployedmbaases
    - name: Create Environment
      fhc:
        action: createEnvironment
        mbaasName: "{{ project_name }}"
        environment: "{{ item.name }}"
      register: deployedenvironments
      with_items: 
        "{{ environments }}"
    # - name: Create to openshift Projects
    #   command: oc new-project "{{ project_name }}"-"{{ item.name }}"
    #   with_items: 
    #     "{{ environments }}"
    - name: Create to openshift Apps
      command: oc new-app -p MBAAS_ROUTER_DNS="{{ project_name }}"-"{{ item.name }}"."{{ openshift.hostname }}" -n "{{ project_name }}"-"{{ item.name }}" -f /Users/philiphayes/projects/innovationLab/tools/rhmap/ansible/fh-mbaas-template-1node.json
      with_items: 
        "{{ environments }}"
    - name: Create RH MAP Project
      fhc:
        action: createProject
        projectName: "{{ project_name }}" 
      register: project_details
    - debug: 
        var: project_details
    - name: Create teams
      fhc:
        action: createTeam
        mbaasName: "{{ project_name }}"
        projectGuid: "{{ project_details.response.guid }}"
        environments: "{{ deployedenvironments.results | map(attribute='id')|join(',') }}"
        mbaases: "{{ deployedmbaases.results | map(attribute='id')|join(',') }}"
    - name: Create User
      fhc:
        action: createUser
        username: test@redhat.com
        email: test@redhat.com 
      register: user_details

