---
  - name: Login to openshift
    command: oc login "{{ openshift.hostname }}" --insecure-skip-tls-verify=true --username="{{ openshift.username }}" --password="{{ openshift.password }}"
  - name: Determine if projects exist
    command: oc get projects "{{ engagement_name }}"-"{{ item.name }}" -o json
    with_items: 
      "{{ environments }}"
    failed_when: false
    changed_when: false
    register: project_test
  - debug: var=project_test
  - name: Create projects
    command: >
      oc
      new-project "{{ engagement_name }}"-"{{ item.item.name }}"
    when: item.rc == 1
    with_items:
    - "{{ project_test.results }}"
  - name: Create Service Keys
    fhc:
      action: createServiceKey
      engagementName: "{{ engagement_name }}"
      environment: "{{ item.item.name }}"
    when: item.rc == 1
    with_items:
    - "{{ project_test.results }}"
    register: serviceKeys
  - debug: var=serviceKeys
  - name: Create openshift Apps
    command: oc new-app -p FHMBAAS_KEY="{{ item.key }}" -p MBAAS_ROUTER_DNS="{{ engagement_name }}"-"{{ item.item.item.name }}"."{{ openshift.dns_name }}" -n "{{ engagement_name }}"-"{{ item.item.item.name }}" -f fh-mbaas-template-1node.json
    register: openshiftApps
    when: item.item.rc == 1
    with_items: 
      "{{ serviceKeys.results }}"
 

    