---
# tasks file for jenkins
- name: Set RH MAP Target
  fhc:
    action: target
    target: "{{ rhmap.domain }}"
- name: Login to RH MAP
  fhc:
    action: login
    username: "{{ rhmap.username }}"
    password: "{{ rhmap.password }}"
- name: Get cloud app git url
  fhc:
    action: getGitUrl
    projectName:  "{{ project_name }}"
    appType: cloud_nodejs
  register: cloud_git_url
- name: update jenkins config.xml
  template: src=config.xml dest=./config-live.xml
- name: create jenkins job
  command: 'curl -u "{{ jenkins.username }}":"{{ jenkins.password }}"  "{{ jenkins.url }}"/createItem?name="{{ project_name }}" -X POST -d "@config-live.xml" -H "Content-Type: application/xml"'