---
# tasks file for jenkins
- name: Set RH MAP Target
  fhc:
    action: target
    target: "{{ rhmap.domain }}"
- name: Login to RH MAP
  fhc:
    action: login
    username: "{{ rhmap.username }}"
    password: "{{ rhmap.password }}"
- name: Get cloud app details
  fhc:
    action: getAppDetails
    projectName:  "{{ item.name }}"
    appType: cloud_nodejs
  register: appDetails
  with_items: 
    "{{ projects }}"
- name: update jenkins cloud app config.xml
  template: src=config.xml dest=./config-{{item.item.name}}.xml
  with_items:
    "{{ appDetails.results }}"
- name: create jenkins job for cloud app
  command: 'curl -u "{{ jenkins.username }}":"{{ jenkins.password }}"  "{{ jenkins.url }}"/createItem?name={{ engagement_name }}-{{ item.name }}-cloud -X POST -d "@config-"{{ item.name }}".xml" -H "Content-Type: application/xml"'
  with_items: 
    "{{ projects }}"
- name: Get client app details
  fhc:
    action: getAppDetails
    projectName:  "{{ item.name }}"
    appType: client_hybrid
  register: cliantAppDetails
  with_items: 
    "{{ projects }}"
- name: update jenkins cloud app config.xml
  template: src=client-config.xml dest=./client-config-{{item.item.name}}.xml
  with_items:
    "{{ cliantAppDetails.results }}"
- name: create jenkins job for cloud app
  command: 'curl -u "{{ jenkins.username }}":"{{ jenkins.password }}"  "{{ jenkins.url }}"/createItem?name={{ engagement_name }}-{{ item.name }}-client -X POST -d "@client-config-"{{ item.name }}".xml" -H "Content-Type: application/xml"'
  with_items: 
    "{{ projects }}"