---
  - name: Set RH MAP Target
    fhc:
      action: target
      target: "{{ rhmap.domain }}"
  - name: Login to RH MAP
    fhc:
      action: login
      username: "{{ rhmap.username }}"
      password: "{{ rhmap.password }}"
  - name: Create MBaaS Target
    fhc:
      action: createMBaaSTarget
      engagementName: "{{ engagement_name }}"
      fhMbaasHost: https://"{{ engagement_name }}"-"{{ item.item.name }}"."{{ openshift.dns_name }}"
      url: https://"{{ openshift.hostname }}":"{{ openshift.port }}"
      openshiftUsername: "{{ openshift.username }}"
      openshiftPassword: "{{ openshift.password }}"
      routerDNSUrl: "{{ openshift.wildcard_dns }}"
      serviceKey: "{{ item.key }}"
      environment: "{{ item.item.name }}"
    when: item.item.rc == 1
    with_items: 
      "{{ serviceKeys.results }}"
  - name: Create Environment
    fhc:
      action: createEnvironment
      engagementName: "{{ engagement_name }}"
      environment: "{{ item.name }}"
    with_items: 
      "{{ environments }}"
  - name: Create RH MAP Project
    fhc:
      action: createProject
      projectName: "{{ item.name }}" 
    register: project_details
    with_items: 
      "{{ projects }}"
  - name: Create teams
    fhc:
      action: createTeam
      engagementName: "{{ engagement_name }}"
      type: "{{ item.type }}"
      name: "{{ item.name }}"
    with_items: 
      "{{ teams }}"
  - name: Create RHMAP Users
    fhc:
      action: createUser
      username: "{{ item.username }}"
      email: "{{ item.email }}" 
    register: user_details
    with_items: 
      "{{ rhmap.users }}"
  - name: Add RHMAP Users to Teams
    fhc:
      action: addUserToTeam
      engagementName: "{{ engagement_name }}"
      username: "{{ item.username }}"
      teamName: "{{ item.team }}" 
    with_items: 
      "{{ rhmap.users }}"
  - name: Add Projects to Teams
    fhc:
      action: updateTeam
      updateType: project
      engagementName: "{{ engagement_name }}"
      newValue: "{{ item[0].name }}"
      teamName: "{{ item[1].name }}" 
    with_nested:
      - "{{ projects }}"
      - "{{ teams }}"
  - name: Add MBaaS Targets to Teams
    fhc:
      action: updateTeam
      updateType: mbaas
      engagementName: "{{ engagement_name }}"
      newValue: "{{ item[0].name }}"
      teamName: "{{ item[1].name }}" 
      isLive: "{{ item[0].is_live }}"
      teamType: "{{ item[1].type }}"
    with_nested:
      - "{{ environments }}"
      - "{{ teams }}"
  - name: Add Environments to Teams
    fhc:
      action: updateTeam
      updateType: environment
      engagementName: "{{ engagement_name }}"
      newValue: "{{ item[0].name }}"
      teamName: "{{ item[1].name }}" 
      isLive: "{{ item[0].is_live }}"
      teamType: "{{ item[1].type }}"
    with_nested:
      - "{{ environments }}"
      - "{{ teams }}"
