---
  - name: Set RH MAP Target
    fhc:
      action: target
      target: "{{ rhmap.domain }}"
  - name: Login to RH MAP
    fhc:
      action: login
      username: "{{ rhmap.username }}"
      password: "{{ rhmap.password }}"
  - name: Create MBaaS Target
    fhc:
      action: createMBaaSTarget
      mbaasName: "{{ project_name }}"
      fhMbaasHost: https://"{{ project_name }}"-"{{ item.name }}"."{{ openshift.hostname }}"
      url: https://"{{ openshift.hostname }}":"{{ openshift.port }}"
      openshiftUsername: "{{ openshift.username }}"
      openshiftPassword: "{{ openshift.password }}"
      routerDNSUrl: "{{ openshift.wildcard_dns }}"
      environment: "{{ item.name }}"
    register: deployedmbaases
    with_items: 
      "{{ environments }}"
  - debug: 
      var: deployedmbaases
  - name: Create Environment
    fhc:
      action: createEnvironment
      mbaasName: "{{ project_name }}"
      environment: "{{ item.name }}"
    register: deployedenvironments
    with_items: 
      "{{ environments }}"
  - name: Create RH MAP Project
    fhc:
      action: createProject
      projectName: "{{ project_name }}" 
    register: project_details
  - debug: 
      var: project_details
  - name: Create teams
    fhc:
      action: createTeam
      mbaasName: "{{ project_name }}"
      type: "{{ item.type }}"
      name: "{{ item.name }}"
      projectGuid: "{{ project_details.response.guid }}"
      environment_permissions: "{{ item.environments  | map(attribute='name')|join(',') }}"
    with_items: 
      "{{ teams }}"
  - name: Create RHMAP Users
    fhc:
      action: createUser
      username: "{{ item.username }}"
      email: "{{ item.email }}" 
    register: user_details
    with_items: 
      "{{ rhmap.users }}"
  - name: Add RHMAP Users to Teams
    fhc:
      action: addUserToTeam
      mbaasName: "{{ project_name }}"
      username: "{{ item.username }}"
      teamName: "{{ item.team }}" 
    with_items: 
      "{{ rhmap.users }}"
